### ISSUE TITLE
Can't open data

### ISSUE THREAD

**Issue by FedeClaudi** [BruntonUWBio/ajile12-nwb-data#3]
Hello, 

Thank you so much for making this amazing dataset openly available. 

I downloaded the data from Dandi and was trying to open it:

```python
from pynwb import NWBHDF5IO
import os

fld = "F:\\PostDoc\\DecodingAlgorithms\\datasets\\AJILE12"
fl = os.listdir(fld)[2]
fid = os.path.join(fld, fl)

io = NWBHDF5IO(fid, mode='r', load_namespaces=False)
nwb = io.read()
```

but I get an error (after a very long stacktreace):
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 9
      6 fid = os.path.join(fld, fl)
      8 io = NWBHDF5IO(fid, mode='r', load_namespaces=False)
----> 9 nwb = io.read()

... omitted ...

KeyError: "'ndx-events' not a namespace"
```

Have you encountered this before? Do you know what the issue might be?

**Comment by stepeter** [comment]
Sorry to hear that you are having issues opening the data. This issue sounds like a problem with the installation of NWBHDF5IO (similar to [this issue](https://github.com/NeurodataWithoutBorders/pynwb/issues/1563)). Do you have the [ndx-events](https://pypi.org/project/ndx-events/) package installed?

The NWBHDF5IO function call might be trying to use that package to load part of the data.

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for getting back to me so rapidly. Following the instructions at the first link worked, thanks!
